app/Http/Controllers/HomeController.php, resources/assets/js/components/Chime.vue
Adding new chimes was not accessible to ALL users, adding new folders was not accessible to new users.
Fixed PHP code for chimes.  Moved new folder vue component outside of a conditional block so it is always visible.
=> Fixing chimes and folders

resources/assets/js/components/presentation_components/FreeResponseStatistics.vue, resources/assets/js/components/presentation_components/HeatmapResponseStatistics.vue, resources/assets/js/components/presentation_components/ImageResponseStatistics.vue, resources/assets/js/components/presentation_components/MultipleChoiceStatistics.vue, resources/assets/js/components/presentation_components/SliderStatistics.vue
=> Remove CSV export from individual questions

cypress/integration/ui/question.test.js, resources/assets/js/components/presentation_components/SliderStatistics.vue, resources/assets/js/components/questions/response/Slider.vue
This tests slider question creation, user response, and viewing results.  
The current implementation of testing the results is a bit hacky, but functional. Later, we could replace it with an image snapshot, if I can get that working.
=> Add test for slider question (qualitative)

resources/assets/js/views/ParticipantPage/ViewModeNotice.vue
=> Participant View Mode now pink! 💖

resources/assets/js/views/HomePage/ChimeCard.vue
- shows "X" to users without edit permissions so that they can remove themselves from chime.
- Optimistic UI for removeChime requests: once the remove button is clicked, the card will be hidden as if it's been deleted. If request fails, the card shows again.  This gives impression of faster UI and prevents double the delete requests if the response time is slower.
=> users can remove themselves from chime

resources/assets/js/views/ParticipantPage/ParticipantPage.vue
After the timeout is exceeded, a message will be displayed and any open questions will be cleared. The socket will also be disconnected. If the student has a valid session, they should just need to reload. Otherwise, they might be prompted to sign in again.
=> add an 8 hour session timeout

resources/assets/js/views/ChimePage/ChimeManagement.vue, resources/assets/js/views/FolderPage/FolderPage.vue, resources/assets/js/views/HomePage/HomePage.vue, resources/assets/js/views/ParticipantPage/ParticipantPage.vue, resources/assets/js/views/QuestionForm/QuestionForm.vue, resources/views/errors/emplid.blade.php
Removes latis@umn.edu and clatel@umn.edu emails.
=> help emails to `latistecharch@umn.edu`, participant emails go to `help`

resources/assets/js/views/HomePage/ChimePanel.vue
=> sync show_folder_title_to_participants

app/Http/Controllers/ChimeController.php, app/Http/Controllers/FolderController.php, app/Http/Controllers/LTI13Handler.php, app/Library/LTI13Processor.php, docs/canvas.md, resources/assets/js/views/ChimePage/ChimeManagement.vue, resources/assets/js/views/FolderPage/FolderPage.vue
A couple fixes from moving to prod deployment of LTI1.3. Missed some stuff in dev testing due to reusing old courses on the dev site I think. Want to get his merged into the vue3 world.
=> Last minute LTI 1.3 changes

composer.lock, docker/7.4/Dockerfile, docker/7.4/start-container, docker/8.0/Dockerfile, docker/8.0/start-container, docker/8.1/Dockerfile, docker/8.1/start-container
- bump version to 1.15.1
- update dockerfiles
=> update laravel sail

docs/asking-questions.md
=> Update true/false docs

docs/accessibility.md
This updates accessibility page in help documentation and link to UMN policy page based on feedback from the Accessibilitiy audit.
=> Update accessibility page 

resources/assets/js/components/ImageHeatmapResponse/ImageHeatmapResponseInputs.vue
=> Fix Heatmap question: center red circle on click location

resources/assets/js/views/ChimePage/ChimeManagement.vue
Waiting for Canvas to come back up to fully test, but here's the PR.
Resolves #478
=> Add spinner for "Force Sync" button to show that sync is in progress

yarn.lock
This reverts `yarn.lock`, which resolves test errors in #704 .
=> revert yarn lock to fix tests

app/Http/Controllers/LTI13Handler.php, composer.json, composer.lock
Fixes a bug where we could potentially load the wrong folder during an LTI launch if that assignment was previously linked to a folder in another chime. (mostly an issue on dev, when db is being poked at)
Also updates the LTI package to use our newer fork, matching our other LTI apps.
=> LTI 1.3 updates to match our other LTI 1.3 apps

.github/workflows/tests.yml
Follow-up on #820 to change to `npm` in test workflow.
=> use npm in test workflow

resources/assets/js/views/PresentPage/PresentPage.vue
Regression after https://github.com/UMN-LATIS/ChimeIn2.0/pull/842
=> fix fullscreen toggle on present page

resources/assets/js/views/QuestionForm/QuestionForm.vue
=> fix: changing question type doesn't fully reset response data

resources/assets/js/app.ts, resources/assets/js/views/ParticipantPage/ParticipantPage.vue
Refactor to add typing to the Participant Page, and fixes type complaints. No intended functionality change.
On dev.
=> add types to ParticipantPage

cypress/e2e/ui/chime.test.js, resources/assets/js/components/FreeResponse/FreeResponseInputs.vue, resources/assets/js/components/ImageHeatmapResponse/ImageHeatmapResponseInputs.vue, resources/assets/js/components/TextHeatmap/TextHeatmapResponseInputs.vue, resources/assets/js/types.ts, resources/assets/js/views/ParticipantPage/ParticipantPrompt.vue
Add types and fixes a few type issues.
=> add types to participant prompt page

app/Http/Controllers/QuestionController.php, routes/web.php
Stacked on #956 
- adds validation to `update` method of QuestionController
- refactor, using route-model binding to do some work for us
no functionality change
=> refactor and add validation to `QuestionController::update` (stacked on #956)

app/Http/Controllers/QuestionController.php, routes/web.php
- validates request data
- refactors, using route-model binding and nullish coalescing to simplify some
No functionality changed.
Stacked on PR #955.
=> refactor and add validation `QuestionController::store` (stacked on #955)

resources/assets/js/views/FolderParticipationPage/FolderParticipationPage.vue, resources/assets/js/views/FolderParticipationPage/UserParticipationRow.vue
Resolves #959
Something like this? Open to feedback on format, layout, etc.
On dev (or will be shortly)
=> Show fraction count on participation report
