.github/workflows/tests.yml
cypress.json
cypress/integration/ui/question.test.js
resources/assets/js/components/presentation_components/SliderStatistics.vue

The slider test fails on CI. This PR adds an intercept and an explicit wait for `PUT` request to `/api/**/response`, which seems to resolve the issue.
I've been unable to replicate the issue locally, but in the CI screenshot of failing tests, it appears that the tall bar is the middle bar (bar 8), rather than the expected bar (bar 5).
My working hypothesis is that there's a race condition between the response sent by the participant and when the response is displayed in the presenter view. I'm also wondering if animation timing plays into this as well... when a new response is received the chart is redrawn and bars slide in from the right.  I could imagine a case where the tests are selecting the bars during the draw.
The working fix is to listen for the PUT response
```js
cy.intercept({ …
```

Fix failing slider test

---

.github/workflows/tests.yml

Always include image snapshots in CI runs.
When passing, we can use images generated by CI if we need to make image updates.
When failing, helpful for troubleshooting the issue.

ci: :construction_worker: Add snapshot uploads to CI

---

composer.json
composer.lock
config/app.php
config/ide-helper.php

Adds [Laravel IDE Helper](https://github.com/barryvdh/laravel-ide-helper) as php dev dependency.
Makes intelephense a bit smarter so that [Unidentified symbol 'Route'](https://github.com/bmewburn/vscode-intelephense/issues/780) goes away in vs code.

add laravel-ide-helper as dev dependency

---

config/permission.php
cypress/support/routes.json
database/factories/ChimeFactory.php
resources/assets/js/app.js
resources/assets/js/components/FreeResponse/FreeResponseInputs.vue
resources/assets/js/components/ImageHeatmapResponse/ImageHeatmapResponseInputs.vue
resources/assets/js/components/MultipleChoice/MultipleChoiceInputs.vue
resources/assets/js/views/FolderPage/FolderPage.vue
resources/assets/js/views/ParticipantPage/ParticipantPage.vue
resources/assets/js/views/ParticipantPage/ParticipantPageViewModeNotice.vue
resources/assets/js/views/ParticipantPage/ViewModeNotice.vue
resources/assets/js/views/QuestionForm/QuestionForm.vue
resources/assets/sass/app.scss

Related to #78:
- Updates ParticipantView page to make it clearer that they're in "Participant View" by adding a wrapper to the view.
- The share URL is included in the bottom. If the chime has an LTI link, it will display a link to the Canvas course `https://canvas.umn.edu/courses/123456` rather than the join link.
- Adds a "Leave Participant View" button which lets users return to previous URL.
Current ParticipantView looks like this:
Also fixes a few regressions after recent refactor:
- imports bootstrap's js, fixing an issue where clicking on a closed tab wouldn't do anything.
- Within an ImageHeatmap question, added a check to make sure target image is loaded before invoking `updateScaledCoordinates`, which resolves an error in the js console.

Add a frame and message when presenter is within participant view.

---

.gitignore
cypress/integration/ui/question.test.js
resources/assets/js/helpers/insertHtmlLabelsIntoGchart.js
resources/assets/js/views/PresentPage/MultipleChoiceStatistics.vue
resources/assets/js/views/PresentPage/SliderStatistics.vue

Restores Google Chart animations on Multiple Choice Stats and Slider Stats pages.
- Adds `cy.wait` to tests to wait for animations to complete.
- Animations overwrite custom HTML `<foreignObject>` labels when they run on MultipleChoice stats. These labels are needed to render equations. I'm using `requestAnimationFrame()` to rerender labels with each step of the animation.
Closes #103.

Return of the animations 🍿

---

resources/assets/js/views/PresentPage/PresentQuestion.vue

Fixes #113.
Went back and forth on hiding vs disabling. Landed on hiding, but let me know if you have a preference.

Hide next/prev buttons if only 1 question

---

resources/assets/js/views/QuestionForm/QuestionForm.vue

Nothing fancy. Just disables save button until there's some `question_text` to prevent empty question submission and 500 error message.
Closes #114

disable save button on QuestionForm if question textbox is empty

---

resources/assets/js/app.js
resources/assets/js/common/tooltip.directive.js

Issue is already fixed in development when we moved away from global jQuery. This just adds a comment about reqs of $.tooltip and inlines directive just in case we refactor or remove jQuery or bootstrap later.
Issue #66 was a tricky one to reproduce.
The error:
```
TypeError: $(...).tooltip is not a function
```
would only occasionally occur on the FreeResponseStatistics page. It turns out that the error can be reproduced by viewing `FreeResponseStatistics` page AFTER  viewing `ImageResponseStatistics` page. 
The problem is that `ImageResponseStatistics` is using a plugin `vue-simple-lightbox`, which – when mounted – reloads jQuery and clobbers `$.tooltip` added by bootstrap.
Here's the offending line in the lightbox component:
```
window.$ = window.jQuery = require('jquery');
```
The …

Add comment and inline tooltip directive

---

.husky/pre-commit
package.json
resources/assets/js/views/HomePage/ChimeCard.vue
resources/assets/js/views/HomePage/ChimePanel.vue

Chime reordering isn't currently supported, but a drag handle was added by **somebody** in a recent UI update. The handle is removed.
Also: Noticed that husky's pre-commit script wasn't catching lint errors that would be caught in CI tests. So, I updated husky pre-commit to run eslint on `vue`, `mjs`, and `cjs` files in addition to `js`.
Before / After

Remove chime drag handle

---

resources/assets/js/views/ChimePage/ChimePage.vue

- prevent shrinkage of chime control button group
- let header container wrap
- move canvas chip above course name
Fixes #126
Long Name
With Canvas Chip
Short name

Fix chime header layout with long names

---

resources/assets/js/views/ChimePage/ChimePage.vue
resources/assets/js/views/ChimePage/NewFolder.vue

This fixes an issue where the "Add Folder" button drops down weird on small screens:
BEFORE / AFTER

fix Add Folder button layout on small screens

---

resources/assets/js/components/Chip.vue
resources/assets/js/views/FolderPage/QuestionCard.vue

Resolves #148. 
- Collapses action buttons (not close) to vertical dots style "more" menu on smaller screen sizes.
- Also, added an action to jump to "Present" view when the card's text is clicked. Previously, there was no action when a card is clicked, which could be confusing – especially if most actions are hidden in the collapsed menu. "Present view" seemed like a good default action on click.

Collapse action buttons to vertical ellipses ⋮ dropdown on small screen sizes

---

app/Http/Controllers/LTIHandler.php
resources/assets/js/views/ParticipantPage/ParticipantPage.vue
resources/views/base.blade.php

Adds a warning for non-Canvas access to Canvas-linked courses. Still allows access to previous questions.
In addition:
- changes "closed questions" to "answered questions"
- removes home link for Canvas-linked courses

add a warning if a student accesses a canvas-linked course directly

---

app/Http/Controllers/ResponseController.php
resources/assets/js/views/ParticipantPage/ParticipantPage.vue
resources/assets/js/views/ParticipantPage/ParticipantPrompt.vue

These are mostly cases where a user loses connectivity while submitting a response, or they've lost the web socket and the question has closed. Previously they got a full backtrace. Now they'll get a nicer error with a clear next step for them.

Return actual errors and draw them more clearly

---

resources/assets/js/components/TextHeatmap/TextHeatmapResponseDisplay.vue
resources/assets/js/helpers/hasSpecializedQuestionDisplay.js
resources/assets/js/views/FolderPage/QuestionCard.vue
resources/assets/js/views/PresentPage/PresentPrompt.vue

This displays the selectable text in addition to the question prompt for text heatmap questions. Previously, it would show in student view or presenter results view. This adds it to the question card and in presenter view, similar to image heatmap and multiple choice questions. 
Closes #157

[Text Heatmap] Show highlightable text in presenter view and on question cards

---

package.json
yarn.lock

This drops deprecated [node-sass](https://github.com/sass/node-sass) dev dependency.
(Ran into a build error with node-sass on my new macbook and realized that we shouldn't need it since we already have sass.)

drop node-sass

---

app/Chime.php
app/User.php
composer.json
composer.lock
cypress/support/routes.json
database/factories/ChimeFactory.php
database/factories/UserFactory.php
database/seeds/ChimesTableSeeder.php
database/seeds/DatabaseSeeder.php
database/seeds/UsersTableSeeder.php
resources/assets/js/helpers/chimeSelectors.js
resources/assets/js/views/HomePage/ChimeCard.vue
resources/views/admin/users/index.blade.php

Currently, the database is seeded with chimes, but these chimes aren't linked to any user (none are seeded), and none of them are LTI flavored. This means testing ChimeIn for LTI linked chimes requires manual setup (and re-setup if you run cypress tests locally when it nukes the database).
So, this PR changes seeding a bit:
- A default admin user is added when the DB is seeded
- The admin user will have 2 seeded chimes attached: one LTI chime and one vanilla chime
Thus:
- A UserSeeder added
- Chime factory now has a `withLTI()` method that can be invoked to turn the chime into an LTI-flavored chime.
- UserFactory and ChimeFactory have been refactored to be in [Laravel 8 factory class](https://laravel.com/docs/8.x/releases#model-factory-classes) style.
- User and Chime classes have the …

Add seed support for LTI chimes

---

.bundlewatch.config.json
.github/workflows/bundlesize.yml
bundlesize.config.json
package.json
yarn.lock

This adds [bundlewatch](https://github.com/bundlewatch/bundlewatch) as a github action to monitor bundle sizes.
The `.bundlewatch.config.json` file is from current production build sizes when gzipped (which is the default), rounded up to the next 10KB.
I also have [a branch with bundlesize](https://github.com/UMN-LATIS/ChimeIn2.0/tree/feature/add-bundle-size) if we want to go that route. Very similar. It seems that bundlewatch is a newer project inspried by bundlesize with maybe a few more features. Like once we merge it with the develop branch, we can start seeing diffs between prs and develop... I think?
Twitter Bootstrap switched from bundlesize to bundlewatch. Bundlesize has way more stars.... so 🤷 .

Monitor bundle size as part of CI

---

app/Library/LTI13Processor.php

As described in tkt.umn.edu/714903, if a Chime is using the half points participation / full points for correct answer model, and the same question is asked multiple times, we don't currently report the highest outcome achieved. Instead, it's basically nondeterministic.
This PR adds a reduce stage to our point computation which uses the max value a student achieved across all the sessions for a course.

Fix for multiple responses not selecting the highest value

---

resources/assets/js/components/ErrorDialog.vue
resources/assets/js/components/Modal.vue

Small changes, but since I spend more time than average on the error page and they've been bothering me for a bit:
- Channeling my inner Steve Krug and adding a big obvious blue button to go to homepage.
- Change email from `clatel@umn.edu` to `help@umn.edu`. (I thought we changed the emails... but maybe that was another app or I missed one?)
- Also changed "get in touch" idiom to a more direct "email help@umn.edu". Idioms can be challenging to understand for non-native speakers.

On error modal, add a big obvious button to go to home page

---

README.md

Change from using local composer to using docker container for installing php deps with composer.
Taken from Sail docs:
https://laravel.com/docs/9.x/sail#executing-composer-commands

Use docker for installing local php deps

---

.github/workflows/tests.yml
app/Http/Controllers/ResponseController.php
composer.json
composer.lock
docker-compose.yml
docker/8.1/Dockerfile
docker/8.1/php.ini
docker/8.1/start-container
docker/8.1/supervisord.conf

- Bump PHP version to "^8.1".
- Change `platform` to 8.1
- Bump Laravel Impersonate package
- bump version, 
- publish php 8.1's dockerfiles, 
- add image-magick package, 
- update `docker-compose.yml` to 8.1.
-  Change PHP version to 8.1
- Add composer option `--ignore-platform-reqs` to ignore packages with outdated stated dependences.
- Set `WWWGROUP` and `WWWUSER` env variables to `1000` here, rather than hardcoding in `docker-compose.yml`.
After updated to PHP8.1, some tests would fail with errors:
```
SQLSTATE[HY000]: General error: 1364 Field 'session_id' doesn't have a default value (SQL: insert into `responses` (`response_info`, `updated_at`, `created_at`) values ({"question_type":"multiple_choice","choice":"<p>3<\/p>"}, 2022-05-02 16:43:22, 2022-05-02 16:43:22))
```
This happened …

Update to PHP 8.1

---

package.json
resources/assets/js/views/FolderPage/FolderPage.vue
yarn.lock

This resolves an issue where a student could view a chime folder edit page if:
- a chime was set to allow participants to view results, and
- the participant navigated to the folder page (if the faculty shared the wrong link, for instance)
This PR checks `folder.student_view` from the API to see if this user is a participant. If so, an error is shown and the loaded questions are reset.  (Note: `folder.student_view` is not returned for presenters and for users that are not members of the chime.)
Question: Should we change the API so that it only returns open questions for folders? Or maybe that might have unintended consequences elsewhere or not worth it at this point?
Closes #248.

Prevent participants from viewing folder page

---

webpack.mix.cjs

Fixes #295
Vue2 and Vue3 handle whitespace differently. In Vue3, the default is to condense whitespace. This sets the the vue config to `preserve` whitespace, so that buttons snuggle less.

Fix whitespace between buttons

---

resources/assets/js/views/ParticipantPage/ParticipantPrompt.vue

Bumps up the contrast with this secondary text so that it's AA compliant.
Closes #383

Increase contrast for question type and saved labels in participant view

---

cypress/integration/ui/guestParticipation.test.js
cypress/integration/ui/imageResponseQuestion.test.js
cypress/integration/ui/question.test.js
resources/assets/js/components/FreeResponse/FreeResponseInputs.vue
resources/assets/js/components/ImageResponse/ImageResponseInputs.vue
resources/assets/js/components/MultipleChoice/MultipleChoiceInputs.vue
resources/assets/js/components/SliderResponse/SliderResponseInputs.vue
resources/assets/js/components/TextHeatmap/TextHeatmapResponseInputs.vue
resources/assets/js/views/ParticipantPage/ParticipantPage.vue
resources/assets/js/views/ParticipantPage/ParticipantPrompt.vue
resources/assets/js/views/ParticipantPage/ParticipantResponse.vue

This improves accessibility headings and labels of question prompts for users using screen readers.
- The question container is given a heading (visually hidden): `ChimeIn Questions`
- The "open question" and "answered" tabs at the top are given `tab` roles.
- question containers have been changed from generic divs to `articles`. The container is given a label of the question type. e.g. `Multiple Choice Question`, similar to how the question appears to sighted users.
- Each question prompt is given a role of heading (level 3). This is based on feedback that most users prefer to navigate a page using headings.
- Each input is associated to the question prompt using `aria-labelledby`, so that the input label is announced to users.
- Range input includes `min` and `max` attributes, to make …

Add labels and headings to questions prompts

---

package.json
resources/assets/js/hooks/useQuill.js
yarn.lock

This enhances image editing functionality within the quill editor, so that users can resize images or add alt attributes:
- Closes https://github.com/UMN-LATIS/ChimeIn2.0/issues/368
- Closes https://github.com/UMN-LATIS/ChimeIn2.0/issues/186
The functionality is added by [@umn-latis/quill-better-image-module](https://github.com/UMN-LATIS/quill-better-image-module), which is based on a [good, but abandoned module for resizing images](https://github.com/kensnyder/quill-image-resize-module). Our fork fixes a few outstanding issues, changes the bundler from old webpack 2 to vite, and adds support for alt text.
Short demo:
Testable version on: <https://cla-chimein-dev.cla.umn.edu/>

Add alt text and image resizing in the question editor

---

app/Chime.php
app/Question.php
app/User.php
cypress/integration/ui/question.test.js

In the current version of VueJS, checkbox inputs using `v-model` no longer coerce a 1 and 0 to true/false values. 
This PR explicitly casts some model values to booleans, and adds a test that checkbox changes persist after saving.
Closes #415 .
@cmcfadden – I just saw your comment on the other issue. We can discuss tomorrow if other approaches might be better.

explicitly cast values as booleans

---

cypress/integration/ui/question.test.js
resources/assets/js/components/ImageHeatmapResponse/ImageHeatmapResponseInputs.vue
resources/assets/js/views/ParticipantPage/ParticipantPage.vue

This PR indirectly resolves an issue #320, where a heatmap response incorrectly renders the click spot at 0,0 on an inactive tab. (e.g. the "answered questions" tab when the page is first loaded, or the "open questions" if a user clicks on the "answered questions" and then resizes the window).
The issue is that `targetImage.clientWidth` is calculated as 0 when a tab pane isn't display.
@cmcfadden and I discussed a few ways of resolving the issue:
1. recalculate the circle coordinates when an image becomes visible perhaps using [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API),
2. don't mount question responses on the participant page until the tab becomes active. Then, once the tab is active, the correct clientWidth will be calculated when …

Fix heatmap question circle rendering on answered questions tab

---

resources/assets/js/views/ChimePage/ChimeManagement.vue

This resolves an in issue where the incorrect user would be deleted. Previously the `deleteUser` method would take an index. But, the index passed was the sortedUsers array, rather than the users array.
This changes the deleteUser method to use the `user.id` instead.

delete user by id instead instead index

---

cypress/integration/ui/happyPath.test.js
resources/assets/js/components/BreadcrumbNav.vue
resources/assets/js/views/ChimePage/ChimePage.vue
resources/assets/js/views/FolderPage/FolderPage.vue

- Adds a breadcrumb component
- Adds breadcrumbs to ChimePage and FolderPage
Breadcrumb component:
Folder Page with Breadcrumb:
Design notes:
- Tried it both with and without current page showing as the last item. I thought it was a little better with the current page. Even though there's duplication of text, I thought it added clarity about the Home > Chime > Folder> Question organization that could aid new users.
- Using a basic "/" as a divider. Tried a chevron, but it looked a little strange with the "back" chevron pointing in the opposite direction.
Definitely weakly held opinions though, so let me know what you think.
Fixes #466

Add breadcrumbs to make it easier to tell the Chime name while in folder

---

.gitmodules
resources/assets/js/layouts/DefaultLayout.vue

Updates vue-template-components' AppFooter, which removes the z-index preventing buttons from being clickable. 
Adds some styles to ChimeIn's `<DefaultLayout>` component to remove the negative margin on AppFooter, preventing it from accidentally overlapping the main area.
See: https://github.com/UMN-LATIS/CLA-vue-template/pull/10
Closes #473

Fix unclickable app footer buttons 

---

resources/assets/js/layouts/DefaultLayout.vue

Changes deprecated `v-deep` to `:deep`.

fix deprecation of `v-deep`. Change to `:deep()`

---

resources/assets/js/components/SliderResponse/SliderResponseInputs.vue

As part of the accessibility review this summer, we changed the min/max of ranged inputs from a generic 0 to 100 to the actual values the presenter set so that they user heard proper values when adjusting the slider. This unfortunately broke the responses, which are computed based on a value between 0 and 100, not the set min/max.
This PR, reverts the min to be 0 and max to be 100. Then, to accommodate users with screenreaders by setting aria values: `aria-valueMin`, `aria-valueMax`, and `aria-valueText.
If a question is  **quantitative**, the `aria-valueText` read will be the same as number in `bubbleText`.  For example, if choices are between `0` and `360` and a user chooses `180` (50%), the user will hear `180` rather than `50`.
If a question is **qualitative**, the text read will be: …

Fix: Slider question not submitting correct value due to min/max

---

package.json
yarn.lock

Stacked on #561. 
This updates to latest version of Vue.

[Stacked on PR #561] bump vue to 3.2.45

---

package.json
yarn.lock

PR stacked on #561.
This updates vue-select to the latest version (that runs on Vue3).

[stacked on PR #561] Update to vue-select-4.0.0-beta.6

---

app/Http/Controllers/ChimeController.php
resources/assets/js/views/ParticipantPage/ParticipantPage.vue

This resolves an issue where participants would see questions in reverse order if they joined AFTER the presenter had clicked "Open All", or when they refreshed their browser.
The intended question order for participants is:
1. `updated_at` in descending order (12:00, 11:00, 10:00), meaning the most recent on top.
2. If there's a tie – as when clicking "Open All" – questions should be sorted by their `order` property in ascending order (1,2,3)
Previously though, `getOpenQuestions` would sort questions by:
- `updated_at` in ascending order, the reverse of what we wanted (10:00, 11:00, 12:00), 
-  but sort by `order` ascending in case of ties (1,2,3).
When presenters would open one question at a time, users would see questions in the correct order because the client side would run a …

fix: question sort order

---

resources/assets/js/views/FolderPage/QuestionCard.vue

Keeps question text as black (instead of blue from a:hover styles).
Fixes #618.

fix: keep question card text black

---

resources/assets/js/helpers/legacyBuildWords.ts
resources/assets/js/views/PresentPage/FreeResponseStatistics.vue
resources/views/layouts/app.blade.php
tsconfig.json
yarn.lock

This fixes a few things with the "Experimental" word cloud processing.
- Sometimes when the Experimental box was checked, the FreeResponseStatistics page  whitescreened with an error related to the compromise nlp package. The issue only occured when building for production (vite dev server seemed to be closing the gap in development mode). This changes `tsconfig` to allow Synthetic Default Imports so that we can `import nlp from "compromise"` even if compromise doesn't have a default export.
- This reverts how NLP works. Previously, the experimental checkbox would use nlp to  only show topics like persons places and things when checked. After discussion, it sounds like this is not the intended behavior – instead the the checkbox should allow for grouping, but also show other words and not …

fix: NLP on Free Response Statistics page + `/admin/users` page formatting fixes

---

app/Http/Controllers/ResponseController.php
cypress/integration/ui/guestParticipation.test.js
resources/assets/js/views/ParticipantPage/ParticipantPage.vue

This resolves #650, where responses were sorted inconsistently on the answered questions tab.
In this PR:
- changes the API to order the responses by most recent `responses.updated_at` value. In cases of a tie, we use the `responses.id` to break the tie, deeming a higher `id` as more recent. (This is mostly needed for testing, when responses are rapid fire and may have the same timestamp.)
- changes client side to prepend new responses to the answered questions section
- adds tests around question response order

Order participant responses in Answered Questions by most recent

---

resources/assets/js/components/ErrorDialog.vue
resources/assets/js/views/ChimePage/ChimePage.vue

This fixes a few issues encountered when working on updating Cypress to v12, specifically when we  [test user promotion/demotion](https://github.com/UMN-LATIS/ChimeIn2.0/blob/develop/cypress/integration/ui/chime.test.js#LL333)
When a user attempts to access a page without permissions, as when we [test user attempts to access page after demotion](https://github.com/UMN-LATIS/ChimeIn2.0/blob/develop/cypress/integration/ui/chime.test.js#LL390-L392C70), the `JoinPanel` component may throw an uncaught exception. This is because the component expects the `chime` prop to contain a well-defined chime, but instead it receives an empty `{}`. The PR only mounts `JoinPanel` if `chime` is an empty object. 
The Modal component complains loudly in the console if it receives a `show` prop that's truthy, …

fix: uncaught exception thrown by `JoinPanel` when `chime` is not well-defined

---

cypress/e2e/ui/chime.test.js
resources/assets/js/views/ChimePage/ChimeManagement.vue

This resolves an issue where users may not realize the roles are editable in the Chime Settings. The select dropdown is always shown and doesn't require a click to begin editing.
Resolves #721

always show user role dropdown select

---

resources/assets/js/types.ts
resources/assets/js/views/PresentPage/FreeResponseStatistics.vue
resources/assets/js/views/PresentPage/HeatmapResponseStatistics.vue
tsconfig.json

This adds pins to heatmap results display, and allows presenters to adjust the opacity and saturation of an image to make the heatmap/pins more visible.
Also: 
- adds some typing to Question and Response types
- fixes an issue where no alt would show for image heatmap. There's no `image_alt` property on heatmap question info, just `image_name`. Using `image_name` as a fallback for now, but see #726 
- fixes an issue where resizing the window wouldn't update the heatmap/pin location
- fixes a type issue with hideWordcloud. (Technically, I guess there could be problems when evaluating `responses.hideWordcloud` since `responses` could be an array?)
Questions:
- Since this is now a pin/heatmap style question, should we update the name? Other ChimeIn like apps call it something like "Drop Pin" …

Add pins to heatmap result statistics, make opacity/saturation configurable

---

cypress/e2e/ui/imageHeatmapQuestion.test.js
resources/assets/js/views/PresentPage/HeatmapResponseStatistics.vue
resources/assets/js/views/QuestionForm/QuestionForm.vue

Image Heatmap question now supports showing pins in addition to heatmaps. This update the name to be "Clickable Image" for clarity.
Defaults are set to show only the heatmap with full image saturation and opacity. That is, image pins will be hidden by default.
Clickable Image question results with defaults:

Change name of "Image Heatmap" to "Clickable Image"

---

deploy.php

`npm ci` takes awhile to run and sometimes deployment fails with a timeout error. This seems to be worse on first deploy when there are more cache misses when fetching packages.
This changes the default timeout from `300` to `600` to give more headroom.

increase timeout to accommodate npm

---

.prettierrc.json
resources/assets/js/helpers/logUnwrappedProxy.ts
resources/assets/js/hooks/useQuestionListener.ts
resources/assets/js/views/PresentPage/PresentPage.vue
resources/assets/js/views/PresentPage/PresentQuestion.vue

This adds Typescript to the `PresentPage` (split off from forthcoming PR for #140).  No functionality change (other than small fixes below).
Fixes:
- an issue where `showJoinInstructions` would always be true because it's in the `methods` section and not `computed`.
- a missing `.value` in `questions.value.length`
- removes unnecessary `parseInt()`  (not an error per-se since JS should coerce the number to a string when invok, but TS complains).
Adds:
- helper function to log the unwrapped version of proxy objects, which removes a bunch of noise when debugging reactive objects and props.

Add TS to PresentPage, fix a few errors

---

resources/assets/js/views/FolderPage/FolderPage.vue

After #843 , the folder toolbar was getting a little cramped. This moves the Open/Close All question buttons to questions section to make a little more room.

move open all / close all question buttons

---

resources/assets/js/types.ts
resources/assets/js/views/ChimePage/ChimePage.vue
resources/assets/js/views/FolderPage/FolderPage.vue

No functionality change. Related to forthcoming PR on issue #818.
Adds TS to Chime and Folder pages fixes type complaints:
- adds existence checks for chimes
- refactors the export/settings panel toggle to work with types
- renames `selected_chime` to  `selected_chime_id` for clarity. Same with `selected_folder`.

Add typescript to ChimePage and FolderPage

---

resources/assets/js/components/NumericResponse/BarChart.vue
resources/assets/js/components/NumericResponse/NumericResponseInputs.vue
resources/assets/js/components/NumericResponse/ScatterPlot.vue
resources/assets/js/icons/IconChartBar.vue
resources/assets/js/icons/IconChartScatter.vue
resources/assets/js/types.ts
resources/assets/js/views/ParticipantPage/ParticipantPrompt.vue
resources/assets/js/views/ParticipantPage/ParticipantResponse.vue
resources/assets/js/views/PresentPage/NumericResponseStatistics.vue
resources/assets/js/views/PresentPage/PresentResults.vue
resources/assets/js/views/QuestionForm/NumericResponseQuestionOptions.vue
resources/assets/js/views/QuestionForm/QuestionForm.vue
resources/assets/sass/app.scss

This adds a new "Numeric" question type gathering univariate or bivariate data and showing results as a histogram or scatter plot.
The histogram has configurable bucket size.
The scatter plot can optionally show regression lines (linear, quadratic, cubic, and exponential).
On dev for testing. Resolves #875. 
Question form:
Participant input:
Results with configurable bucket size:
Question form:
Participant input:
Scatter plot with trendline:
width="600" />

Add numeric question types for histograms and scatter plots

---

resources/assets/js/components/NumberInputGroup.vue
resources/assets/js/components/NumericResponse/BarChartResponseInputs.vue
resources/assets/js/components/NumericResponse/NumericResponseInputs.vue
resources/assets/js/components/NumericResponse/RangeChart.vue
resources/assets/js/components/NumericResponse/RangeChartResponseInputs.vue
resources/assets/js/components/NumericResponse/ScatterPlotResponseInput.vue
resources/assets/js/components/NumericResponse/ScatterPlotResponseInputs.vue
resources/assets/js/icons/IconChartRange.vue
resources/assets/js/types.ts
resources/assets/js/views/PresentPage/NumericResponseStatistics.vue
resources/assets/js/views/QuestionForm/NumericResponseQuestionOptions.vue

Adds a option for numeric response to show a range chart.
Previously there was a question of whether or not it'd be better to type the chart something more abstract like "univariate"/"bivariate". After this, my sense is that it's better to handle charts on case by basis.
Here, a range question (e.g. "Estimate how much building the thing will cost?") is univariate so we only need one variable label from the question form – like other univariate data. But, on the user form, we gather two numbers min and max (`xRange`), which differs from the the other univariate histogram question (where we only ask the user for 1 number).
On dev for testing.

Add range chart

---

package-lock.json
package.json

fix added to: https://github.com/UMN-LATIS/quill-better-image-module/commit/151cbd57d941151cb0684156ca01c85f37b1caaa
closes #428

fix: Image Resize Controls don't hide when clicking away

---

app/Http/Controllers/HomeController.php
app/Http/Controllers/ImpersonateController.php
app/Http/Middleware/ShibInjection.php
app/User.php
composer.json
composer.lock
config/app.php
resources/assets/js/components/ImpersonationBanner.vue
resources/assets/js/layouts/DefaultLayout.vue
resources/assets/js/types.ts
routes/web.php

- Adds an Impersonation banner (similar to Bluesheet) when user is impersonating another user, including the impersonated user's name, email, and a Leave Impersonation button.
- Removes the old impersonation Lab404 package as we're now relying on Nova's impersonation system.
- Adds a route `/impersonate/stop` to stop impersonation.
Also:
- Fixes an issue where the impersonating admin would see their own user name/email rather than the user's on the home page because shib injection middleware overrides any impersonated user info. This PR just skips shib injection when impersonating a user.

Add impersonation banner with "Leave Impersonation" button

---

app/Http/Controllers/ChimeController.php
cypress/e2e/api/chimeUser.js
cypress/e2e/api/chimeUsers.test.js

- Fixes an issue where a participant user could change a chime members or permissions with sync endpoint
- Validates request data
- adds tests for the sync api endpoint

check that user can edit chime before syncing users

---

app/Http/Controllers/ChimeController.php
cypress/e2e/api/chimeUser.js
cypress/e2e/api/chimeUsers.test.js
resources/assets/js/common/api.ts
resources/assets/js/views/ChimePage/ChimeManagement.vue
routes/web.php

Resolves #513: syncUsers can trigger an n+1 query. 
We already have endpoints for updating and removing users from a Chime, so this changes the frontend to use the update/remove endpoints rather than syncing the full member list on each update. Then `syncUsers` is removed since it's not used elsewhere.

fix: n+1 query on permission change

---

resources/assets/js/views/PresentPage/VWordCloud.vue

Fixes #594
Sometimes a presenter's websocket connection breaks and their wordcloud no longer receives updates. In a large session, I witnessed the presenter repeatedly click the "refresh" button trying to see the updates, but the refresh button just rerendered the wordcloud and did not reload the whole page.
This changes the wordcloud to have two buttons: "shuffle" which rerender to the cloud,  and "refresh" to reload the page.

Add separate shuffle and refresh buttons to wordcloud

---

app/Http/Controllers/FolderController.php
resources/assets/js/views/FolderPage/FolderPage.vue

Fixes #319
- Updates `importQuestions` so the of the imported questions added after the existing questions
- validates the `folder_id`
- checks that the user has permissions for both current chime  and the source folder's chime
- closes the folder settings panel on successful import so that the user has some signifier that the import was completed

fix: imported questions don't have reindexed sort order

---

resources/assets/js/views/ChimePage/ChimeManagement.vue

when select value changes sometimes the old `user.permission_number` is passed `updateChimeUserPermission` function. This parses the updated value directly from `event.target`.

fix: sometimes user permissions don't update

---

resources/assets/js/common/api.ts
resources/assets/js/hooks/useQuestionListener.ts
resources/assets/js/views/ChimePage/ChimeManagement.vue
resources/assets/js/views/FolderPage/FolderPage.vue

Fixes #653 
When a user without Presenter permissions tries to view the folder page, they may see a spinner if they're not a member of the chime.
This shows an error message anytime a `403` is returned from our attempt to fetch folders.
The `useQuestionListener` composable is updated to catch and expose any errors as a ref: `fetchError`. We watch this ref and dispatch an error message when there's an error.

show error on folder page if user is not presenter

---

resources/assets/js/views/PresentPage/toWordFrequencyLookup.test.ts
resources/assets/js/views/PresentPage/toWordFrequencyLookup.ts

- fixes filtering so that it applies to quoted text as well
- adds tests
Fixes #655

fix: responses in quotes don't filter from wordcloud

---

.eslintrc.cjs
resources/assets/js/views/ChimePage/ChimeManagement.vue

Fixes ChimeIn tests failing at eslint check. 
- changes eslint from "error" (default) to "warn" when there's an unused variable in a vue file.
- removes the unused `index` variable regardless

fix(test): only warn on unused variables

---

resources/assets/sass/app.scss

Quill2 always uses `<ol>` ([by design](https://github.com/slab/quill/issues/3957)) for both ordered and unordered lists. This is causing all lists in ChimeIn to be rendered as ordered list.
The proper fix is to use Quill's `getSemanticHTML` when saving updates – currently we're saving Quill's markup.
But, for now, this CSS should be a valid workaround. The `:not(.ql-editor ...)` is there to avoid rendering double-bullets within the editor, because Quill handles in-editor rendering just fine.
On dev for testing.
https://github.com/user-attachments/assets/29b043b3-eaf5-42b1-ad43-46daad280e85

fix: unordered lists with using quill will show as ordered

---

resources/assets/js/components/NumericResponse/BarChartResponseInputs.vue
resources/assets/js/components/NumericResponse/NumericResponseInputs.vue
resources/assets/js/components/NumericResponse/RangeChartResponseInputs.vue
resources/assets/js/components/NumericResponse/ScatterPlotResponseInputs.vue
resources/assets/js/helpers/getNormedNumericQuestionOptions.ts
resources/assets/js/types.ts
resources/assets/js/views/PresentPage/NumericResponseStatistics.vue
resources/assets/js/views/QuestionForm/NumericResponseQuestionOptions.vue

resolves #948 
- `x_axis_label` is now correctly typed as optional, so that we correctly get red squiggles in code when it's missing.
- Fall back to `X` as an label in statistics and input.
On dev for testing

handle missing x-axis labels in numeric questions

---

app/Http/Controllers/FolderController.php

Resolves #952 
This regression was introduced in #945, where we moved a question to the end of a folder when current folder id isn't the destination folder id.
To determine if we need to move the question, we compare the current folder id and the destination folder id. However, we have a type mismatch because we're getting the current folder id from the route:
```
// $currentFolderId is a string
$currentFolderId = $req->route('folder_id');
// $destFolderId is an int
$destFolderId = $req->get('folder_id');
```
The solution is to cast `$currentFolderId` as an `int`.

fix: question move to end after editing

---

app/Http/Controllers/QuestionController.php
routes/web.php

Stacked on #957 
Refactor `destroy` similar to `update` and `store` methods: let Route-Model binding do some work for us.
No functionality change.

refactor `QuestionController::destroy` (stacked on #957)
